### ISSUE TITLE
How to install Rainicorn tools?

### ISSUE THREAD

**Issue by AlexRadch** [RustDT/Rainicorn#1]
I don't see any instructions.
`cargo install Rainicorn` return next error 

```
could not find `Rainicorn` in `registry https://github.com/rust-lang/crates.io-index`
```

**Comment by AlexRadch** [comment]
Why you do not add Rainicorn to https://crates.io/ ?

**Comment by bruno-medeiros** [comment]
Hum, I don't see the point of going through all the hassle of crates.io submission and management, just for users to avoid typing `--git https://github.com/RustDT/Rainicorn` in the command line :sleepy:  It's not a priority at least
