### ISSUE TITLE
Extend to do build?

### ISSUE THREAD

**Issue by johalun** [RustDT/Rainicorn#2]
Hi! This is great! Thank you.

I wonder, would it be easy to extend it do to "cargo build" on save and report build errors the same way (similar to Rust-linter for Atom) or is it better to make a separate tool for that?

**Comment by bruno-medeiros** [comment]
I'm not entirely familiar with Rust-linter, but that seems to be an IDE-specific tool (for Atom). Rainicorn is meant to be IDE-independent, in fact there isn't much for Rainicorn to do in the _"cargo build" on save_ scenario. The IDE can just call `cargo build` directly. 

The only thing Rainicorn could do would be to parse the `cargo build` errors output, and output it in a different format, more easy for IDEs to parse. Is that what you meant?

As for RustDT, it can already be configured to run the build on save, but there a few issues with that functionality.

**Comment by johalun** [comment]
> The only thing Rainicorn could do would be to parse the cargo build errors output, and output it in a different format, more easy for IDEs to parse. Is that what you meant?

Yes. In addition to the syntax error checker it would be nice if it also could show build errors. But since building is not something you wanna do in the background too often, it might be good to only do it on save, or at most once every few seconds. 

> Rainicorn is meant to be IDE-independent...

So there is no Eclipse-specific formatting in Rainicorn? But there must be something in between right? Some tool that converts the Rainicorn output to match Eclipse input format? Is this something RustDT is doing?

**Comment by bruno-medeiros** [comment]
Yes, RustDT is what reads the Rainicorn output. I made up the format, it wasn't a format built-in to Eclipse itself.

As for RustDT doing a build on every save, I could re-enable that functionality (it was there before, but removed now), but it needs some more tweaking first to work well.

**Comment by bruno-medeiros** [comment]
This functionality is subsumed by RLS: https://github.com/jonathandturner/rls , and the LSP protocol's PublishDiagnostics Notification.
